volumes:
    LocalSettings:
        driver: local
    images:
        driver: local
    skins:
        driver: local
    extensions:
        driver: local
    db:
        driver: local
    initdb:
        driver: local

networks:
  net:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: ${NET_SUBNET:-192.168.8.224/28} #(8.201-8.206, 207)
     driver_opts:
       com.docker.network.bridge.name: mw_net

services:
    mw.db:
        image: 'mariadb:10'
        container_name: mw.db
        hostname: db
        restart: always
        networks:
          - net
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: no
            MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-yes}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: 'Europe/Amsterdam'
        volumes:
          - db:/var/lib/mysql
          - initdb:/docker-entrypoint-initdb.d

    mw.php:
        hostname: mw.php
        container_name: mw.php
        restart: always
        networks:
          - net
        ports:
          - ${MW_HOSTPORT:-127.0.0.1:8100}:80
        image: ghcr.io/vslcatena/docker-mediawiki:${MW_VERSION:-lts}
        pull_policy: always
        build:
            dockerfile: Dockerfile
            context: ./src
            args:
                VERSION: lts
        depends_on:
            - mw.db
        environment:
           MW_SITE_SERVER: '${MW_SITE_SERVER}'
           MW_DB_NAME: '${MYSQL_DATABASE:-wiki}'
           MW_DB_USER: '${MYSQL_USER:-wikiuser}'
           MW_DB_PASS: '${MYSQL_PASSWORD:-password}'
           PHP_LOG_ERRORS: Off
           PHP_ERROR_REPORTING: E_ALL & ~E_DEPRECATED & ~E_STRICT
           TZ: Europe/Amsterdam
        volumes:
            - LocalSettings:/var/www/html/conf.d
            - images:/var/www/html/images
            - skins:/var/www/html/skins
            - extensions:/var/www/html/extensions
