volumes:
    images:
        driver: local
    skins:
        driver: local
    extensions:
        driver: local
    db:
        driver: local

networks:
  net:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: ${NET_SUBNET:-192.168.8.224/28} #(8.201-8.206, 207)
     driver_opts:
       com.docker.network.bridge.name: mw_net
       
services:
    mw.db:
        image: 'mariadb:10'
        container_name: mw.db
        hostname: db
        restart: always
        networks:
          - net
        environment:
            # MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            # MYSQL_DATABASE: 
            # MYSQL_USER: 
            # MYSQL_PASSWORD:
            TZ: 'Europe/Amsterdam'
        volumes:
          - db:/var/lib/mysql
#        ports:
#          - 127.0.0.1:8101:3306
        
    mw.php:
        hostname: mw.php
        container_name: mw.php
        restart: always
        networks:
          - net
        ports:
          - 127.0.0.1:8100:80
        image: ghcr.io/vslcatena/docker-mediawiki:lts # mediawiki:lts
        build:
            dockerfile: Dockerfile        
            context: ./src
            args:
                VERSION: lts
        depends_on:
            - mw.db
        environment:
           MW_SITE_SERVER: '${MW_SITE_SERVER}'
           MW_DB_NAME: '${MYSQL_DATABASE:-wiki}'
           MW_DB_USER: '${MYSQL_USER:-wikiuser}'
           MW_DB_PASS: '${MYSQL_PASSWORD:-password}'
           PHP_LOG_ERRORS: On
           PHP_ERROR_REPORTING: E_ALL & ~E_DEPRECATED & ~E_STRICT #Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
           TZ: Europe/Amsterdam
        volumes:
            - images:/var/www/html/images
            - skins:/var/www/html/skins
            - extensions:/var/www/html/extensions
            # After initial setup, download LocalSettings.php to the same directory as
            # this yaml and uncomment the following line and use compose to restart
            # the mediawiki service
            - ./LocalSettings.php:/var/www/html/LocalSettings.php
            # This key also defines the name of the database host used during setup instead of the default localhost
